# @package _global_
# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override /hydra/hydra_logging: colorlog
  - override /hydra/job_logging: colorlog


hydra:
  run:
    dir: ${exp_dir}/hydra
  sweep:
    dir: ${exp_dir}/hydra
    subdir: ID${hydra.job.id}
  job:
    config:
      override_dirname:
        exclude_keys:
          - trainer
          - trainer.devices
          - trainer.num_nodes
          - callbacks
          - debug