# @package _global_

defaults:
  - default.yaml 

DATASETS:
  name: mixall

  TRAIN: 
    HUMAN-LAB-AUG-TRAIN:
      WEIGHT: .5
    HUMAN-LAB-TRAIN:
      WEIGHT: .5

    HUMAN-KIT-AUG-TRAIN:
      WEIGHT: .5
    HUMAN-KIT-TRAIN:
      WEIGHT: .5

    ADT-TRAIN:
      WEIGHT: 0.25
    
    G1-LAB-TRAIN: 
      WEIGHT: 2.0

  VAL:
    G1-LAB-VAL:
      WEIGHT: 1.0      